# Generated by Django 4.2.7 on 2023-11-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxInformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressbarmodel',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
