# Generated by Django 4.2.7 on 2023-11-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Represents Section in mobile app', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('field_type', models.CharField(choices=[('CharField', 'CharField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('IntegerField', 'IntegerField'), ('BooleanField', 'BooleanField'), ('FileField', 'FileField')], db_index=True, max_length=13)),
                ('frontend_field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('multiple_select', 'MultipleSelect'), ('file', 'File'), ('check_box', 'CheckBox'), ('radio', 'Radio')], db_index=True, default='text', max_length=15)),
                ('django_validation', models.JSONField(blank=True, default=dict)),
                ('field_data', models.JSONField(blank=True, default=dict)),
                ('form_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DigbForms.formstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
